# Generated by Django 6.0.2 on 2026-02-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='slot',
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
        migrations.DeleteModel(
            name='patients',
        ),
        migrations.DeleteModel(
            name='mapping',
        ),
        migrations.DeleteModel(
            name='slots',
        ),
    ]
