# Generated by Django 6.0.2 on 2026-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='address',
        ),
        migrations.AddField(
            model_name='mapping',
            name='is_booked',
            field=models.BooleanField(default=True),
        ),
    ]
